version: '3'

services:
  postgres:
    image: 'postgres:latest'

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'

  node-server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_DATABASE=postgres
      - PG_PASSWORD=postgres_password
      - PG_PORT=5432

  react-app:
    build:
      dockerfile: Dockerfile.dev
      context: ./react-app
    volumes:
      - /app/node_modules
      - ./react-app:/app